<?php

return [
    'profile'         => 'Profile',
    'dashboard'       => 'Boshqaruv paneli',
    'add'             => "Qo'shish",
    'create'          => "Yaratish",
    'edit'            => 'Tahrirlash',
    'save'            => 'Saqlash',
    'saved'           => 'Saqlandi',
    'saved_error'     => 'Saqlashda xatolik',
    'filters'         => 'Filtrlar',
    'search'          => 'Qidirmoq',
    'reset'           => 'Tozalash',
    'total'           => 'Jami',
    'deleted'         => 'O\'chirilgan',
    'delete'          => 'O\'chirish',
    'deleting'        => 'Oʻchirilmoqda',
    'download'        => 'Yuklab olish',
    'export'          => 'Eksport',
    'cancel'          => 'Bekor qilish',
    'confirm'         => 'Tasdiqlash',
    'close'           => 'Yopish',
    'confirm_message' => 'Siz rostdan ham bu amalni bajarishni istaysizmi?',
    'back'            => 'Orqaga',
    'more'            => 'Batafsil',
    'all_sections'    => "Barcha bo'limlar",
    'file'            => 'Fayl',
    'user'            => 'Foydalanuvchi',
    'changes'         => "O'zgarishlar",
    'last_changes'    => 'Oxirgi o\'zgarishlar',
    'date'            => 'Sana',
    'field'           => 'Maydon',
    'before'          => 'Oldin',
    'after'           => 'Keyin',
    'loading'         => 'Yuklanmoqda...',
    'notfound'        => 'Hech narsa topilmadi',
    'collapse_menu'   => 'Yopish/Ochish',
    '404'             => 'Xyustonda muammoli sahifa topilmadi',
    'copied'          => 'Ko‘chirildi!',
    'notifications'   => [
        'title'            => 'Bildirishnomalar',
        'mark_as_read_all' => 'Barchasini o\'qilgan deb belgilash',
        'mark_as_read'     => 'O\'qilgan deb belgilash',
    ],
    'login'           => [
        'title'         => ':moonshine_title saytiga xush kelibsiz!',
        'description'   => 'Iltimos, hisobingizga kiring',
        'authorization' => 'Avtorizatsiya',
        'remember_me'   => 'Meni eslab qol',
        'login'         => 'Kirish',
        'logout'        => 'Chiqish',
        'username'      => 'Username',
        'email'         => 'E-mail',
        'password'      => 'Parol',
        'or_socials'    => 'yoki',
    ],
    'resource'        => [
        "income_types"    => "Kirim turlari",
        "clients"         => "Mijozlar",
        "product_income"  => "Mahsulot kirimlari",
        "sellers"         => "Sotuvchilar",
        "products"        => "Mahsulotlar",
        'system'          => 'Tizim',
        "category"        => "Kategoriyalar",
        "stores"          => "Do'konlar",
        'role'            => 'Rol',
        'name'            => 'Nomi',
        'email'           => 'E-mail',
        'password'        => 'Parol',
        'repeat_password' => 'Parolni takrorlang',
        'avatar'          => 'Avatar',
        'created_at'      => 'Yaratilgan vaqti',
        'admins_title'    => 'Administratorlar',
        'role_title'      => 'Rollar',
        'role_name'       => 'Rol nomi',
        "store_users"     => "Hodim va ishchilar",

        'main_information' => 'Asosiy ma\'lumotlar',
        'change_password'  => 'Parolni o\'zgartirish',

        'link_socialite'   => 'Sotsial tarmoqlar',
        'linked_socialite' => "Hisob bog'langan",

        'queued' => 'Navbatda',

        'export' => [
            'exported' => 'Fayl eksport qilindi',
        ],

        'import' => [
            'imported'                => 'Fayl import qilindi',
            'file_required'           => 'Fayl talab qilinadi',
            'extension_not_supported' => 'Faylning formati qo\'llab-quvvatlanmaydi',
        ],
    ],

    "store_name"          => "Do'kon nomi",
    "store"               => "Do'kon",
    "category"            => "Kategoriya",
    "store_name_optional" => "Do'kon nomi (ixtiyoriy)",
    "status"              => "Holat",
    "description"         => "Tavsif",
    "address"             => "Manzil",
    "phone"               => "Telefon",
    "category_name"       => "Kategoriya nomi",
    "image"               => "Rasm",
    "sort"                => "Saralash",
    "name"                => "Nomi",
    "bar_code"            => "Shtrix-kod",
    "uuid"                => "UUID",
    "seller_name"         => "Sotuvchi nomi",
    "seller"              => "Sotuvchi",
    "full_name"           => "To'liq ismi",
    "birth_date"          => "Tug'ilgan sana",
    "product"             => "Mahsulot",
    "quantity"            => "Miqdori",
    "buy_price"           => "Sotib olish narxi",
    "sell_price"          => "Sotish narxi",
    "currency"            => " so'm",
    "characteristics"     => "Xususiyatlari",
];
